version: '3.4'
services:

  app:
    build:
      context: .docker/php-fpm
      args:
        - DOCKER_USER_UID=${DOCKER_USER_UID}
        - DOCKER_USER_GID=${DOCKER_USER_GID}
        - XDEBUG_VERSION=2.7.2
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    user: ${DOCKER_USER_UID}:${DOCKER_USER_GID}

  nginx:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 80:80
      - 443:443

  mysql:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306

volumes:
  dbdata: {}
